INSERT INTO "public"."spells" ("id", "character_id", "name", "level", "school", "casting_time", "range", "components", "duration", "description", "prepared", "created_at", "updated_at", "source", "classes", "ritual", "concentration", "effect_type", "base_dice", "include_spell_mod", "damage_type", "upcast_dice_per_level", "cantrip_dice_increases") VALUES ('005fe291-83ed-40c7-bb84-f2065ee6b352', null, 'Zombaria cruel', '0', 'Encantamento', 'Ação', '60 pés', 'V', 'Instantânea', 'Você libera uma série de insultos misturados a encantamentos sutis em uma criatura que você possa ver ou ouvir dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou sofrerá 1d6 de dano Psíquico e terá Desvantagem na próxima jogada de ataque que fizer antes do final do seu próximo turno.
Melhoria de Truque. O dano aumenta em 1d6 quando você atinge os níveis 5 ( 2d6 ), 11 ( 3d6 ) e 17 ( 4d6 ).', 'false', '2025-09-27 18:47:32.750808+00', '2025-10-01 14:17:53.325775+00', 'PHB 2024', null, 'false', 'false', 'damage', '1d6', null, 'Psíquico', '1d6', '[{"dice": "2d6", "level": 5}, {"dice": "3d6", "level": 11}, {"dice": "4d6", "level": 17}]'), ('16fd81a2-4963-4945-a332-736c74840a59', null, 'Mão de Mago', '0', 'Conjuração', 'Ação', '30 pés', 'V, S', '1 minuto', 'Uma mão espectral flutuante aparece em um ponto à sua escolha dentro do alcance. A mão permanece ativa enquanto durar o efeito. A mão desaparece se estiver a mais de 9 metros de distância de você ou se você conjurar esta magia novamente.
Ao lançar o feitiço, você pode usar a mão para manipular um objeto, abrir uma porta ou recipiente destrancado, guardar ou recuperar um item de um recipiente aberto ou despejar o conteúdo de um frasco.
Com uma ação de Magia nos seus turnos posteriores, você pode controlar a mão novamente. Como parte dessa ação, você pode mover a mão até 9 metros.
A mão não pode atacar, ativar itens mágicos ou carregar mais de 4,5 kg.', 'false', '2025-09-27 18:46:14.783935+00', '2025-09-27 23:24:40.059587+00', 'PHB 2024', null, 'false', 'false', null, null, 'false', null, null, null), ('252c2b4a-09b3-4f83-9367-3bdac6226c44', null, 'Toque Frio', '0', 'Necromancia', 'Ação', 'Toque', 'V, S', 'Instantânea', 'Canalizando o frio da sepultura, faça um ataque mágico corpo a corpo contra um alvo ao seu alcance. Ao acertar, o alvo sofre 1d10 de dano Necrótico e não pode recuperar Pontos de Vida até o final do seu próximo turno.', 'false', '2025-10-01 18:44:01.784781+00', '2025-10-01 21:44:04.849917+00', 'PHB 2024', null, 'false', 'true', 'damage', '1d10', null, 'Necrótico', null, '[{"dice": "2d10", "level": 5}, {"dice": "3d10", "level": 11}, {"dice": "4d10", "level": 17}]'), ('25b345e3-2094-4715-b9fa-f7d5ae880757', null, 'Luzes dançantes', '0', 'Ilusão', 'Ação', '120', 'V, S, M (um pouco de fósforo)', 'Concentração , até 1 minuto', 'Você cria até quatro luzes do tamanho de tochas dentro do alcance, fazendo-as parecer tochas, lanternas ou orbes brilhantes que pairam durante a duração. Alternativamente, você combina as quatro luzes em uma forma Média brilhante que lembra vagamente a humana. Qualquer que seja a forma escolhida, cada luz emite Luz Fraca em um raio de 3 metros.

Como uma Ação Bônus , você pode mover as luzes até 18 metros para um espaço dentro do alcance. Uma luz deve estar a até 6 metros de outra luz criada por esta magia, e uma luz desaparece se exceder o alcance da magia.', 'false', '2025-10-01 18:45:10.391886+00', '2025-10-01 21:45:13.463308+00', 'PHB 2024', null, 'false', 'true', null, null, null, null, null, null), ('5f05959b-1bb0-4d8f-984f-35c9446ab05b', null, 'Amigos', '0', 'Encantamento', 'Ação', '10 pés', 'P, M (alguma maquiagem)', 'Concentração , até 1 minuto', 'Você emana magicamente um sentimento de amizade por uma criatura que você possa ver dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou ter a condição Encantado durante a duração. O alvo obtém sucesso automaticamente se não for um Humanoide, se você estiver lutando contra ele ou se você tiver conjurado esta magia nele nas últimas 24 horas.

A magia termina mais cedo se o alvo sofrer dano ou se você fizer uma jogada de ataque, causar dano ou forçar alguém a fazer um teste de resistência. Quando a magia termina, o alvo sabe que foi enfeitiçado por você.', 'false', '2025-09-27 18:49:08.766511+00', '2025-09-27 23:24:50.994614+00', 'PHB 2024', null, 'false', 'true', null, null, 'false', null, null, null), ('60cef881-e07b-4a69-9e3c-b6bdc9218a94', null, 'Farpas prateadas', '1', 'Encantamento', 'Reação, que você realiza quando uma criatura que você pode ver a até 18 metros de você obtém sucesso em uma jogada de ataque, um teste de habilidade ou um teste de resistência.', '60 pés', 'V', 'Instantânea', 'Você distrai magicamente a criatura que desencadeou o efeito e transforma sua incerteza momentânea em encorajamento para outra criatura. A criatura que desencadeou o efeito deve rolar novamente o d20 e usar a menor jogada.

Você pode então escolher uma criatura diferente que esteja visível dentro do alcance (você pode escolher). A criatura escolhida tem vantagem na próxima jogada de ataque, teste de habilidade ou teste de resistência que fizer dentro de 1 minuto. Uma criatura só pode ser fortalecida com um uso desta magia por vez.', 'false', '2025-09-27 18:52:36.666656+00', '2025-09-27 23:24:58.081717+00', 'PHB 2024', null, 'false', 'false', null, null, 'false', null, null, null), ('91f74b3f-85d3-45d2-8c0f-5ce1ab3b7627', null, 'Proteção da Lâmina', '0', 'Abjuração', 'Ação', 'Próprio', 'V, S', 'Concentração , até 1 minuto', 'Sempre que uma criatura faz uma jogada de ataque contra você antes que a magia termine, o atacante subtrai 1d4 da jogada de ataque.', 'false', '2025-10-01 18:42:51.515822+00', '2025-10-01 21:42:54.580331+00', 'PHB 2024', null, 'false', 'true', null, null, null, null, null, null), ('98d2e47e-a2dc-4b29-af15-187b9eed0290', null, 'Respingo ácido', '0', 'Evocação', 'Ação', '60', 'V, S', 'Instantânea', 'Você cria uma bolha ácida em um ponto dentro do alcance, onde ela explode em uma Esfera de 1,5 metro de raio . Cada criatura naquela Esfera deve ser bem-sucedida em um teste de resistência de Destreza ou sofrerá 1d6 de dano de Ácido.
Melhoria de Truque. O dano aumenta em 1d6 quando você atinge os níveis 5 ( 2d6 ), 11 ( 3d6 ) e 17 ( 4d6 )', 'false', '2025-10-01 18:41:38.185019+00', '2025-10-01 21:41:41.220073+00', 'PHB 2024', null, 'false', 'false', 'damage', '1d6', null, 'Ácido', null, '[{"dice": "2d6", "level": 5}, {"dice": "3d6", "level": 11}, {"dice": "4d6", "level": 17}]'), ('f50e7c51-1edf-4512-975c-f70a1048e0f3', null, 'A risada horrível de Tasha', '1', 'Encantamento', 'Ação', '30 pés', 'V, S, M (uma torta e uma pena)', 'Concentração , até 1 minuto', 'Uma criatura à sua escolha que você possa ver dentro do alcance realiza um teste de resistência de Sabedoria. Em caso de falha, ela fica sob as condições Prostrado e Incapacitado enquanto durar o teste. Durante esse tempo, ela ri incontrolavelmente se for capaz de rir, e não pode encerrar a condição Prostrado em si mesma.

Ao final de cada turno e sempre que sofrer dano, ele realiza outro teste de resistência de Sabedoria. O alvo tem Vantagem no teste se este for acionado por dano. Em caso de sucesso, a magia termina.

Usando um Espaço de Magia de Nível Superior. Você pode escolher uma criatura adicional para cada nível de espaço de magia acima de 1.', 'false', '2025-09-27 18:54:42.889001+00', '2025-09-27 23:25:02.141531+00', 'PHB 2024', null, 'false', 'true', null, null, 'false', null, null, null), ('f731521e-a886-4717-b72d-d32b188d5ef3', null, 'Druidismo', '0', 'Transmutação', 'Ação', '30', 'V, S', 'Instantânea', 'Sussurrando aos espíritos da natureza, você cria um dos seguintes efeitos dentro do alcance.

Sensor de Clima. Você cria um pequeno efeito sensorial inofensivo que prevê como estará o clima em sua localização nas próximas 24 horas. O efeito pode se manifestar como uma esfera dourada para céu limpo, uma nuvem para chuva, flocos de neve caindo para neve e assim por diante. Este efeito persiste por 1 rodada.

Florescer. Você faz uma flor desabrochar instantaneamente, uma vagem de semente se abrir ou um broto de folha florescer.

Efeito Sensorial. Você cria um efeito sensorial inofensivo, como folhas caindo, fadas dançando espectralmente, uma brisa suave, o som de um animal ou o leve odor de gambá. O efeito deve caber em um Cubo de 1,5 m .

Brincadeira com fogo. Você acende ou apaga uma vela, uma tocha ou uma fogueira.', 'false', '2025-10-01 18:45:52.680461+00', '2025-10-01 21:45:55.710222+00', 'PHB 2024', null, 'false', 'false', null, null, null, null, null, null);